Feker ik75 Undetected Keyboard Fix (#281)
* feat: added ik75 still error

- quantum/vial_ensure_keycode.h:164:1: error: static assertion failed: ""
 _Static_assert(KC_LSPO == 0x5CD7, "");

* fix: add via settings

* fix: disable unused matrix for firmware size

- remove matrix that causes error

* feat: use home as default layout

* fix: rotary click is K4F should be 4,15 not 0,14

* refactor: disable some matrix to free some bytes

* feat: remove more bad rgb for bigger memory and add restart button (not bootloader)

* fix: undetected keyboard when pc shutdown

- sometimes need to replug or reflash